import { weddingCapabilities } from '../../core/app/permissions.js';
import { readPlannerStorageKey, writePlannerStorageKey } from '../../services/planner-cloud.js';

const STORAGE_KEY='planificador_bodas_presupuesto_v5_etiquetas';
let activeContext=null,state=null,search='',mountEpoch=0,saving=false;
const fallbackTags=[{id:'tag_urgent',name:'Urgente',color:'#d9485f'},{id:'tag_wait',name:'Puede esperar',color:'#d5a72c'},{id:'tag_later',name:'No es necesario',color:'#2fa36b'}];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;");
const n=v=>Number.isFinite(Number(v))?Math.max(0,Number(v)):0;
function normalized(value){const v=value&&typeof value==='object'?value:{};return{...v,settings:{totalBudget:n(v.settings?.totalBudget),guestCount:Math.max(0,Math.floor(n(v.settings?.guestCount))),currency:['PEN','USD','EUR'].includes(v.settings?.currency)?v.settings.currency:'PEN'},categories:Array.isArray(v.categories)?v.categories:[],items:Array.isArray(v.items)?v.items:[],tags:Array.isArray(v.tags)&&v.tags.length?v.tags:fallbackTags,openCategories:Array.isArray(v.openCategories)?v.openCategories:[]}}
function money(v){return new Intl.NumberFormat('es-PE',{style:'currency',currency:state?.settings?.currency||'PEN',minimumFractionDigits:2,maximumFractionDigits:2}).format(n(v))}
function symbol(){return({PEN:'S/',USD:'$',EUR:'€'})[state?.settings?.currency]||state?.settings?.currency||'S/'}
function totals(items=state.items){return items.reduce((a,x)=>({planned:a.planned+n(x.planned),quoted:a.quoted+n(x.quoted),paid:a.paid+n(x.paid),guarantee:a.guarantee+n(x.guarantee)}),{planned:0,quoted:0,paid:0,guarantee:0})}
function tagById(id){return state.tags.find(t=>String(t.id)===String(id))}
function itemMeta(item){return[item.provider,item.paymentDate,({pending:'Pendiente',quoted:'Cotizado',partial:'Pago parcial',paid:'Pagado'})[item.status]].filter(Boolean).join(' · ')}
const makeId=prefix=>prefix+'_'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));
function canEdit(){return weddingCapabilities(activeContext?.role).canEdit}
async function persist(message='Guardado en Firebase'){if(!activeContext||saving||!canEdit())return;saving=true;const root=document.querySelector('[data-module-view="presupuesto"]'),status=root?.querySelector('[data-budget-state]');if(status)status.textContent='Guardando en Firebase…';try{await writePlannerStorageKey(activeContext,STORAGE_KEY,state);if(status)status.textContent=message;window.dispatchEvent(new CustomEvent('migrandia:datachange',{detail:{module:'presupuesto',weddingId:activeContext.id}}))}catch(error){if(status)status.textContent=error?.message||'No se pudo guardar en Firebase.';throw error}finally{saving=false}}
function categoryName(id){return state.categories.find(c=>String(c.id)===String(id))?.name||'—'}
function itemBalance(item){return Math.max(0,(n(item.quoted)||n(item.planned))-n(item.paid))}
function tagIds(item){return Array.isArray(item.tagIds)?item.tagIds.map(String):[]}
function formField(label,control){return '<label class="budget-form-field"><span>'+label+'</span>'+control+'</label>'}
function openEditor(kind,payload={}){if(!canEdit())return;const root=document.querySelector('[data-module-view="presupuesto"]'),dialog=root?.querySelector('[data-budget-dialog]');if(!dialog)return;const title=root.querySelector('[data-budget-dialog-title]'),body=root.querySelector('[data-budget-dialog-body]'),footer=root.querySelector('[data-budget-dialog-footer]');let html='';
 if(kind==='item'){const item=payload.item||{},categoryId=payload.categoryId||item.categoryId||state.categories[0]?.id||'';title.textContent=item.id?'Editar gasto':'Nuevo gasto';html='<form data-budget-edit-form data-kind="item" data-id="'+esc(item.id||'')+'">'+formField('Gasto','<input name="name" required maxlength="140" value="'+esc(item.name||'')+'">')+'<div class="budget-form-grid">'+formField('Categoría','<select name="categoryId">'+state.categories.map(cat=>'<option value="'+esc(cat.id)+'"'+(String(cat.id)===String(categoryId)?' selected':'')+'>'+esc(cat.name||'Categoría')+'</option>').join('')+'</select>')+formField('Estado','<select name="status">'+[['pending','Pendiente'],['quoted','Cotizado'],['partial','Pago parcial'],['paid','Pagado']].map(([v,l])=>'<option value="'+v+'"'+((item.status||'pending')===v?' selected':'')+'>'+l+'</option>').join('')+'</select>')+'</div><div class="budget-form-grid">'+formField('Presupuestado','<input name="planned" type="number" min="0" step="0.01" value="'+n(item.planned)+'">')+formField('Cotizado','<input name="quoted" type="number" min="0" step="0.01" value="'+n(item.quoted)+'">')+'</div><div class="budget-form-grid">'+formField('Pagado','<input name="paid" type="number" min="0" step="0.01" value="'+n(item.paid)+'">')+formField('Garantía','<input name="guarantee" type="number" min="0" step="0.01" value="'+n(item.guarantee)+'">')+'</div><div class="budget-form-grid">'+formField('Proveedor','<input name="provider" maxlength="140" value="'+esc(item.provider||'')+'">')+formField('Fecha de pago','<input name="paymentDate" type="date" value="'+esc(item.paymentDate||'')+'">')+'</div>'+formField('Etiquetas','<div class="budget-tag-picker">'+state.tags.map(tag=>'<label style="--tag:'+esc(tag.color||'#777')+'"><input type="checkbox" name="tagIds" value="'+esc(tag.id)+'"'+(tagIds(item).includes(String(tag.id))?' checked':'')+'><i></i><span>'+esc(tag.name||'Etiqueta')+'</span></label>').join('')+'</div>')+formField('Notas','<textarea name="notes" rows="3" maxlength="700">'+esc(item.notes||'')+'</textarea>')+'</form>'}
 else if(kind==='category'){const cat=payload.category||{};title.textContent=cat.id?'Editar categoría':'Nueva categoría';html='<form data-budget-edit-form data-kind="category" data-id="'+esc(cat.id||'')+'">'+formField('Nombre','<input name="name" required maxlength="80" value="'+esc(cat.name||'')+'">')+formField('Descripción','<input name="description" maxlength="180" value="'+esc(cat.description||'')+'">')+formField('Icono','<input name="icon" maxlength="4" value="'+esc(cat.icon||'•')+'">')+'</form>'}
 else if(kind==='tag'){const tag=payload.tag||{};title.textContent=tag.id?'Editar etiqueta':'Nueva etiqueta';html='<form data-budget-edit-form data-kind="tag" data-id="'+esc(tag.id||'')+'">'+formField('Nombre','<input name="name" required maxlength="50" value="'+esc(tag.name||'')+'">')+formField('Color','<input name="color" type="color" value="'+esc(/^#[0-9a-f]{6}$/i.test(tag.color||'')?tag.color:'#7f8962')+'">')+'</form>'}
 body.innerHTML=html;footer.innerHTML='<button type="button" data-budget-close>Cancelar</button><button class="budget-save" type="submit" form="'+(body.querySelector('form')?.id||'')+'" data-budget-save>Guardar cambios</button>';const form=body.querySelector('form');if(form){form.id='budgetEditorForm';footer.querySelector('[data-budget-save]').setAttribute('form','budgetEditorForm')}dialog.showModal();form?.querySelector('input,select,textarea')?.focus()}

function render(){
 const root=document.querySelector('[data-module-view="presupuesto"]');if(!root||!state)return;
 const t=totals(),budget=n(state.settings.totalBudget),available=Math.max(0,budget-t.paid),pct=budget?Math.min(100,Math.round(t.paid*100/budget)):0,guests=n(state.settings.guestCount);
 root.querySelector('[data-budget-available]').textContent=money(available);root.querySelector('[data-budget-symbol]').textContent=symbol();root.querySelector('[data-budget-total]').textContent=money(budget).replace(symbol(),'').trim();root.querySelector('[data-budget-currency]').textContent=state.settings.currency;root.querySelector('[data-budget-guests]').textContent=String(guests);root.querySelector('[data-budget-progress]').style.width=pct+'%';root.querySelector('[data-budget-progress-text]').textContent=pct+'% del presupuesto pagado';root.querySelector('[data-budget-per-guest]').textContent=guests?money(budget/guests)+' por invitado':'Sin invitados definidos';
 [['planned',t.planned],['quoted',t.quoted],['paid',t.paid],['guarantee',t.guarantee]].forEach(([k,v])=>root.querySelector('[data-budget-'+k+']').textContent=money(v));
 root.querySelector('[data-budget-planned-note]').textContent=budget?money(Math.max(0,budget-t.planned))+' sin asignar':'Sin presupuesto definido';root.querySelector('[data-budget-quoted-note]').textContent=t.quoted?'Cotizaciones registradas':'Sin cotizaciones';root.querySelector('[data-budget-paid-note]').textContent=t.paid?'Pagos registrados':'Sin adelantos registrados';root.querySelector('[data-budget-guarantee-note]').textContent=t.guarantee?'Garantías registradas':'Sin garantías registradas';root.querySelector('[data-budget-analysis]').textContent=budget?(t.paid>budget?'Los pagos registrados superan el presupuesto total.':money(available)+' disponibles después de los pagos registrados.'):'Define el presupuesto total y registra los gastos para ver el análisis.';
 root.querySelector('[data-budget-tags]').innerHTML=state.tags.map(tag=>{const count=state.items.filter(i=>tagIds(i).includes(String(tag.id))).length;return '<button type="button" class="budget-tag" data-budget-edit-tag data-tag-id="'+esc(tag.id)+'" style="--tag:'+esc(tag.color||'#777')+'"><span><i></i>'+esc(tag.name||'Etiqueta')+'</span><b>'+count+'</b></button>'}).join('');
 const needle=search.toLocaleLowerCase('es');const open=new Set(state.openCategories.map(String));
 root.querySelector('[data-budget-categories]').innerHTML=state.categories.map(cat=>{const all=state.items.filter(i=>String(i.categoryId)===String(cat.id));const items=all.filter(i=>!needle||[cat.name,i.name,i.provider,i.notes].join(' ').toLocaleLowerCase('es').includes(needle));if(needle&&!items.length&&!String(cat.name||'').toLocaleLowerCase('es').includes(needle))return'';const ct=totals(all),isOpen=open.has(String(cat.id))||Boolean(needle);return '<article class="budget-category'+(isOpen?' open':'')+'" data-category-id="'+esc(cat.id)+'"><header data-budget-toggle><div class="budget-category-title"><span class="budget-category-icon">'+esc(cat.icon||'•')+'</span><div><h3>'+esc(cat.name||'Categoría')+'</h3><p>'+esc(cat.description||'')+'</p></div></div><div class="budget-category-actions">'+(canEdit()?'<button type="button" data-budget-edit-category>Editar</button><button type="button" data-budget-add-item>＋ Gasto</button>':'')+'<button class="budget-chevron" type="button">'+(isOpen?'⌃':'⌄')+'</button></div></header><div class="budget-category-summary"><div><span>Presupuestado</span><strong>'+money(ct.planned)+'</strong></div><div><span>Cotizado</span><strong>'+money(ct.quoted)+'</strong></div><div><span>Pagado</span><strong>'+money(ct.paid)+'</strong></div></div><div class="budget-category-body"><div class="budget-item-list">'+(items.length?items.map(item=>itemMarkup(item)).join(''):'<div class="budget-empty">Sin gastos en esta categoría.</div>')+'</div></div></article>'}).join('')||'<div class="budget-empty">No hay resultados.</div>';
}
function itemMarkup(item){const tags=tagIds(item).map(tagById).filter(Boolean);const balance=itemBalance(item);return '<div class="budget-item" data-item-id="'+esc(item.id)+'"><div class="budget-item-main"><strong>'+esc(item.name||'Gasto')+'</strong><small>'+esc(itemMeta(item))+'</small><div class="budget-item-tags">'+tags.map(t=>'<span class="budget-item-tag" style="--tag:'+esc(t.color||'#777')+'">'+esc(t.name)+'</span>').join('')+'</div></div>'+[['Presup.',item.planned],['Cotizado',item.quoted],['Pagado',item.paid],['Saldo',balance]].map(([l,v])=>'<div class="budget-item-value"><span>'+l+'</span><strong>'+money(v)+'</strong></div>').join('')+'<button class="budget-item-action" type="button" data-budget-view-item aria-label="'+(canEdit()?'Editar gasto':'Ver gasto')+'">'+(canEdit()?'✎':'＋')+'</button></div>'}
function showDetails(item){const root=document.querySelector('[data-module-view="presupuesto"]'),dialog=root.querySelector('[data-budget-dialog]');root.querySelector('[data-budget-dialog-title]').textContent=item.name||'Gasto';root.querySelector('[data-budget-dialog-body]').innerHTML='<dl>'+[['Categoría',categoryName(item.categoryId)],['Presupuestado',money(item.planned)],['Cotizado',money(item.quoted)],['Pagado',money(item.paid)],['Saldo',money(itemBalance(item))],['Garantía',money(item.guarantee)],['Proveedor',item.provider||'—'],['Fecha de pago',item.paymentDate||'—'],['Estado',item.status||'pending'],['Notas',item.notes||'—']].map(([a,b])=>'<div><dt>'+esc(a)+'</dt><dd>'+esc(b)+'</dd></div>').join('')+'</dl>';root.querySelector('[data-budget-dialog-footer]').innerHTML='<button type="button" data-budget-close>Cerrar</button>';dialog.showModal()}
async function handleSubmit(event){if(!event.target.matches('[data-budget-edit-form]'))return;event.preventDefault();if(!canEdit())return;const form=event.target,data=new FormData(form),kind=form.dataset.kind,id=form.dataset.id;
 if(kind==='item'){const patch={name:String(data.get('name')||'').trim(),categoryId:String(data.get('categoryId')||''),status:String(data.get('status')||'pending'),planned:n(data.get('planned')),quoted:n(data.get('quoted')),paid:n(data.get('paid')),guarantee:n(data.get('guarantee')),provider:String(data.get('provider')||'').trim(),paymentDate:String(data.get('paymentDate')||''),tagIds:data.getAll('tagIds').map(String),notes:String(data.get('notes')||'').trim()};if(!patch.name)return;const index=state.items.findIndex(x=>String(x.id)===String(id));if(index>=0)state.items[index]={...state.items[index],...patch};else state.items.push({id:makeId('item'),...patch});}
 if(kind==='category'){const patch={name:String(data.get('name')||'').trim(),description:String(data.get('description')||'').trim(),icon:String(data.get('icon')||'•').trim()||'•'};if(!patch.name)return;const index=state.categories.findIndex(x=>String(x.id)===String(id));if(index>=0)state.categories[index]={...state.categories[index],...patch};else state.categories.push({id:makeId('cat'),...patch});}
 if(kind==='tag'){const patch={name:String(data.get('name')||'').trim(),color:String(data.get('color')||'#7f8962')};if(!patch.name)return;const index=state.tags.findIndex(x=>String(x.id)===String(id));if(index>=0)state.tags[index]={...state.tags[index],...patch};else state.tags.push({id:makeId('tag'),...patch});}
 form.closest('dialog')?.close();render();await persist(kind==='item'?'Gasto guardado':kind==='category'?'Categoría guardada':'Etiqueta guardada')}
function bind(root){if(root.dataset.budgetBound)return;root.dataset.budgetBound='true';root.addEventListener('submit',handleSubmit);root.addEventListener('input',e=>{if(e.target.matches('[data-budget-search]')){search=e.target.value;render();const input=root.querySelector('[data-budget-search]');input.focus();input.setSelectionRange(search.length,search.length)}});root.addEventListener('click',e=>{if(e.target.closest('[data-budget-close]')){root.querySelector('[data-budget-dialog]')?.close();return}
 const row=e.target.closest('[data-item-id]');if(row&&e.target.closest('[data-budget-view-item]')){const item=state.items.find(i=>String(i.id)===row.dataset.itemId);if(item)(canEdit()?openEditor('item',{item}):showDetails(item));return}
 const tag=e.target.closest('[data-budget-edit-tag]');if(tag){const value=state.tags.find(t=>String(t.id)===String(tag.dataset.tagId));if(value)openEditor('tag',{tag:value});return}
 const card=e.target.closest('[data-category-id]');if(card&&e.target.closest('[data-budget-edit-category]')){const cat=state.categories.find(x=>String(x.id)===String(card.dataset.categoryId));if(cat)openEditor('category',{category:cat});return}
 if(card&&e.target.closest('[data-budget-add-item]')){openEditor('item',{categoryId:card.dataset.categoryId});return}
 if(card&&e.target.closest('[data-budget-toggle]')){const id=card.dataset.categoryId,list=new Set(state.openCategories.map(String));list.has(id)?list.delete(id):list.add(id);state.openCategories=[...list];render();return}
 if(e.target.closest('[data-budget-new-item]')){openEditor('item');return}if(e.target.closest('[data-budget-new-category]')){openEditor('category');return}if(e.target.closest('[data-budget-new-tag]')){openEditor('tag');return}
 if(e.target.closest('[data-budget-export]')){const rows=[['Categoría','Gasto','Presupuestado','Cotizado','Pagado','Garantía','Proveedor','Estado']];state.items.forEach(i=>rows.push([categoryName(i.categoryId),i.name,n(i.planned),n(i.quoted),n(i.paid),n(i.guarantee),i.provider||'',i.status||'']));const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='presupuesto-boda.csv';a.click();URL.revokeObjectURL(url)}})}
async function mountPresupuesto(context){const root=document.querySelector('[data-module-view="presupuesto"]');if(!root||!context?.id)return;const epoch=++mountEpoch;activeContext=context;root.innerHTML='<div class="budget-empty">Cargando Presupuesto desde Firebase…</div>';try{const [template,stored]=await Promise.all([fetch(new URL('./index.html',import.meta.url)).then(r=>{if(!r.ok)throw new Error('No se pudo cargar la interfaz.');return r.text()}),readPlannerStorageKey(context,STORAGE_KEY)]);if(epoch!==mountEpoch||activeContext?.id!==context.id)return;root.innerHTML=template;state=normalized(stored);search='';bind(root);render();const editable=weddingCapabilities(context.role).canEdit;root.querySelector('[data-budget-state]').textContent=editable?'Datos de la boda activa · edición habilitada':'Datos reales de Firebase · solo lectura';}catch(error){if(epoch!==mountEpoch)return;root.innerHTML='<div class="budget-empty">No se pudo cargar el Presupuesto: '+esc(error?.message||'Error de lectura')+'</div>'}}
export{mountPresupuesto};