import { weddingCapabilities } from '../../core/app/permissions.js';
import { readPlannerStorageKey } from '../../services/planner-cloud.js';

const STORAGE_KEY='planificador_bodas_presupuesto_v5_etiquetas';
let activeContext=null,state=null,search='',mountEpoch=0;
const fallbackTags=[{id:'tag_urgent',name:'Urgente',color:'#d9485f'},{id:'tag_wait',name:'Puede esperar',color:'#d5a72c'},{id:'tag_later',name:'No es necesario',color:'#2fa36b'}];
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#039;");
const n=v=>Number.isFinite(Number(v))?Math.max(0,Number(v)):0;
function normalized(value){const v=value&&typeof value==='object'?value:{};return{...v,settings:{totalBudget:n(v.settings?.totalBudget),guestCount:Math.max(0,Math.floor(n(v.settings?.guestCount))),currency:['PEN','USD','EUR'].includes(v.settings?.currency)?v.settings.currency:'PEN'},categories:Array.isArray(v.categories)?v.categories:[],items:Array.isArray(v.items)?v.items:[],tags:Array.isArray(v.tags)&&v.tags.length?v.tags:fallbackTags,openCategories:Array.isArray(v.openCategories)?v.openCategories:[]}}
function money(v){return new Intl.NumberFormat('es-PE',{style:'currency',currency:state?.settings?.currency||'PEN',minimumFractionDigits:2,maximumFractionDigits:2}).format(n(v))}
function symbol(){return({PEN:'S/',USD:'$',EUR:'€'})[state?.settings?.currency]||state?.settings?.currency||'S/'}
function totals(items=state.items){return items.reduce((a,x)=>({planned:a.planned+n(x.planned),quoted:a.quoted+n(x.quoted),paid:a.paid+n(x.paid),guarantee:a.guarantee+n(x.guarantee)}),{planned:0,quoted:0,paid:0,guarantee:0})}
function tagById(id){return state.tags.find(t=>String(t.id)===String(id))}
function itemMeta(item){return[item.provider,item.paymentDate,({pending:'Pendiente',quoted:'Cotizado',partial:'Pago parcial',paid:'Pagado'})[item.status]].filter(Boolean).join(' · ')}
function render(){
 const root=document.querySelector('[data-module-view="presupuesto"]');if(!root||!state)return;
 const t=totals(),budget=n(state.settings.totalBudget),available=Math.max(0,budget-t.paid),pct=budget?Math.min(100,Math.round(t.paid*100/budget)):0,guests=n(state.settings.guestCount);
 root.querySelector('[data-budget-available]').textContent=money(available);root.querySelector('[data-budget-symbol]').textContent=symbol();root.querySelector('[data-budget-total]').textContent=money(budget).replace(symbol(),'').trim();root.querySelector('[data-budget-currency]').textContent=state.settings.currency;root.querySelector('[data-budget-guests]').textContent=String(guests);root.querySelector('[data-budget-progress]').style.width=pct+'%';root.querySelector('[data-budget-progress-text]').textContent=pct+'% del presupuesto pagado';root.querySelector('[data-budget-per-guest]').textContent=guests?money(budget/guests)+' por invitado':'Sin invitados definidos';
 [['planned',t.planned],['quoted',t.quoted],['paid',t.paid],['guarantee',t.guarantee]].forEach(([k,v])=>root.querySelector('[data-budget-'+k+']').textContent=money(v));
 root.querySelector('[data-budget-planned-note]').textContent=budget?money(Math.max(0,budget-t.planned))+' sin asignar':'Sin presupuesto definido';root.querySelector('[data-budget-quoted-note]').textContent=t.quoted?'Cotizaciones registradas':'Sin cotizaciones';root.querySelector('[data-budget-paid-note]').textContent=t.paid?'Pagos registrados':'Sin adelantos registrados';root.querySelector('[data-budget-guarantee-note]').textContent=t.guarantee?'Garantías registradas':'Sin garantías registradas';root.querySelector('[data-budget-analysis]').textContent=budget?(t.paid>budget?'Los pagos registrados superan el presupuesto total.':money(available)+' disponibles después de los pagos registrados.'):'Define el presupuesto total y registra los gastos para ver el análisis.';
 root.querySelector('[data-budget-tags]').innerHTML=state.tags.map(tag=>{const count=state.items.filter(i=>Array.isArray(i.tagIds)&&i.tagIds.map(String).includes(String(tag.id))).length;return '<div class="budget-tag" style="--tag:'+esc(tag.color||'#777')+'"><span><i></i>'+esc(tag.name||'Etiqueta')+'</span><b>'+count+'</b></div>'}).join('');
 const needle=search.toLocaleLowerCase('es');const open=new Set(state.openCategories.map(String));
 root.querySelector('[data-budget-categories]').innerHTML=state.categories.map(cat=>{const all=state.items.filter(i=>String(i.categoryId)===String(cat.id));const items=all.filter(i=>!needle||[cat.name,i.name,i.provider,i.notes].join(' ').toLocaleLowerCase('es').includes(needle));if(needle&&!items.length&&!String(cat.name||'').toLocaleLowerCase('es').includes(needle))return'';const ct=totals(all),isOpen=open.has(String(cat.id))||Boolean(needle);return '<article class="budget-category'+(isOpen?' open':'')+'" data-category-id="'+esc(cat.id)+'"><header data-budget-toggle><div class="budget-category-title"><span class="budget-category-icon">'+esc(cat.icon||'•')+'</span><div><h3>'+esc(cat.name||'Categoría')+'</h3><p>'+esc(cat.description||'')+'</p></div></div><div class="budget-category-actions"><button type="button" data-budget-add-item>＋ Gasto</button><button class="budget-chevron" type="button">'+(isOpen?'⌃':'⌄')+'</button></div></header><div class="budget-category-summary"><div><span>Presupuestado</span><strong>'+money(ct.planned)+'</strong></div><div><span>Cotizado</span><strong>'+money(ct.quoted)+'</strong></div><div><span>Pagado</span><strong>'+money(ct.paid)+'</strong></div></div><div class="budget-category-body"><div class="budget-item-list">'+(items.length?items.map(item=>itemMarkup(item)).join(''):'<div class="budget-empty">Sin gastos en esta categoría.</div>')+'</div></div></article>'}).join('')||'<div class="budget-empty">No hay resultados.</div>';
}
function itemMarkup(item){const tags=(Array.isArray(item.tagIds)?item.tagIds:[]).map(tagById).filter(Boolean);const balance=Math.max(0,(n(item.quoted)||n(item.planned))-n(item.paid));return '<div class="budget-item" data-item-id="'+esc(item.id)+'"><div class="budget-item-main"><strong>'+esc(item.name||'Gasto')+'</strong><small>'+esc(itemMeta(item))+'</small><div class="budget-item-tags">'+tags.map(t=>'<span class="budget-item-tag" style="--tag:'+esc(t.color||'#777')+'">'+esc(t.name)+'</span>').join('')+'</div></div>'+[['Presup.',item.planned],['Cotizado',item.quoted],['Pagado',item.paid],['Saldo',balance]].map(([l,v])=>'<div class="budget-item-value"><span>'+l+'</span><strong>'+money(v)+'</strong></div>').join('')+'<button class="budget-item-action" type="button" data-budget-view-item>＋</button></div>'}
function showDetails(item){const root=document.querySelector('[data-module-view="presupuesto"]'),dialog=root.querySelector('[data-budget-dialog]');root.querySelector('[data-budget-dialog-title]').textContent=item.name||'Gasto';root.querySelector('[data-budget-dialog-body]').innerHTML='<dl>'+[['Categoría',state.categories.find(c=>String(c.id)===String(item.categoryId))?.name||'—'],['Presupuestado',money(item.planned)],['Cotizado',money(item.quoted)],['Pagado',money(item.paid)],['Garantía',money(item.guarantee)],['Proveedor',item.provider||'—'],['Fecha de pago',item.paymentDate||'—'],['Estado',item.status||'pending'],['Notas',item.notes||'—']].map(([a,b])=>'<div><dt>'+esc(a)+'</dt><dd>'+esc(b)+'</dd></div>').join('')+'</dl>';dialog.showModal()}
function bind(root){if(root.dataset.budgetBound)return;root.dataset.budgetBound='true';root.addEventListener('input',e=>{if(e.target.matches('[data-budget-search]')){search=e.target.value;render();const input=root.querySelector('[data-budget-search]');input.focus();input.setSelectionRange(search.length,search.length)}});root.addEventListener('click',e=>{if(e.target.closest('[data-budget-close]')){root.querySelector('[data-budget-dialog]')?.close();return}const row=e.target.closest('[data-item-id]');if(row&&e.target.closest('[data-budget-view-item]')){const item=state.items.find(i=>String(i.id)===row.dataset.itemId);if(item)showDetails(item);return}const card=e.target.closest('[data-category-id]');if(card&&e.target.closest('[data-budget-toggle]')&&!e.target.closest('[data-budget-add-item]')){const id=card.dataset.categoryId,list=new Set(state.openCategories.map(String));list.has(id)?list.delete(id):list.add(id);state.openCategories=[...list];render();return}if(e.target.closest('[data-budget-new-item],[data-budget-new-category],[data-budget-new-tag],[data-budget-add-item]')){root.querySelector('[data-budget-state]').textContent='Edición se habilitará en la siguiente etapa; Firebase permanece en solo lectura.';return}if(e.target.closest('[data-budget-export]')){const rows=[['Categoría','Gasto','Presupuestado','Cotizado','Pagado','Garantía','Proveedor','Estado']];state.items.forEach(i=>rows.push([state.categories.find(c=>String(c.id)===String(i.categoryId))?.name||'',i.name,n(i.planned),n(i.quoted),n(i.paid),n(i.guarantee),i.provider||'',i.status||'']));const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='presupuesto-boda.csv';a.click();URL.revokeObjectURL(url)}})}
async function mountPresupuesto(context){const root=document.querySelector('[data-module-view="presupuesto"]');if(!root||!context?.id)return;const epoch=++mountEpoch;activeContext=context;root.innerHTML='<div class="budget-empty">Cargando Presupuesto desde Firebase…</div>';try{const [template,stored]=await Promise.all([fetch(new URL('./index.html',import.meta.url)).then(r=>{if(!r.ok)throw new Error('No se pudo cargar la interfaz.');return r.text()}),readPlannerStorageKey(context,STORAGE_KEY)]);if(epoch!==mountEpoch||activeContext?.id!==context.id)return;root.innerHTML=template;state=normalized(stored);search='';bind(root);render();const editable=weddingCapabilities(context.role).canEdit;root.querySelector('[data-budget-state]').textContent=editable?'Datos reales de Firebase · edición aún no habilitada':'Datos reales de Firebase · solo lectura';}catch(error){if(epoch!==mountEpoch)return;root.innerHTML='<div class="budget-empty">No se pudo cargar el Presupuesto: '+esc(error?.message||'Error de lectura')+'</div>'}}
export{mountPresupuesto};