import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js';import{getAuth,GoogleAuthProvider,signInWithPopup,signInWithEmailAndPassword,signOut,onAuthStateChanged,setPersistence,browserLocalPersistence}from'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
const config={apiKey:'AIzaSyDCRuQgMjnm7KcAN_qo8AHPD3ueyis4-LY',authDomain:'migrandia.firebaseapp.com',projectId:'migrandia',storageBucket:'migrandia.firebasestorage.app',messagingSenderId:'7432985765',appId:'1:7432985765:web:b3a4844f41ac2a1376c14c'};
const app=getApps()[0]||initializeApp(config),auth=getAuth(app);setPersistence(auth,browserLocalPersistence).catch(console.warn);
const $=id=>document.getElementById(id),menu=$('menuButton'),drawer=$('drawer'),overlay=$('authOverlay'),status=$('authStatus'),email=$('authEmail'),password=$('authPassword'),google=$('googleLoginButton'),login=$('emailLoginButton'),close=$('authCloseButton'),logout=$('logoutButton'),card=$('accountCard'),avatar=$('accountAvatar'),name=$('accountName'),mail=$('accountEmail');
function setMenu(open){document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open));drawer.setAttribute('aria-hidden',String(!open))}
function setAuth(open,msg=''){overlay.classList.toggle('show',open);overlay.setAttribute('aria-hidden',String(!open));status.textContent=msg}
function err(e){const c=String(e?.code||'');if(c.includes('invalid-credential')||c.includes('user-not-found')||c.includes('wrong-password'))return'Correo o contraseña incorrectos.';if(c.includes('popup-closed'))return'Ventana de Google cerrada.';return'No se pudo iniciar sesión. Inténtalo nuevamente.'}
menu.addEventListener('click',()=>{if(!auth.currentUser){setAuth(true);return}setMenu(!document.body.classList.contains('menu-open'))});
close.addEventListener('click',()=>setAuth(false));overlay.addEventListener('click',e=>{if(e.target===overlay)setAuth(false)});
login.addEventListener('click',async()=>{status.textContent='Ingresando…';try{await signInWithEmailAndPassword(auth,email.value.trim(),password.value);setAuth(false);setMenu(true)}catch(e){status.textContent=err(e)}});
password.addEventListener('keydown',e=>{if(e.key==='Enter')login.click()});
google.addEventListener('click',async()=>{status.textContent='Elige tu cuenta de Google…';const p=new GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});try{await signInWithPopup(auth,p);setAuth(false);setMenu(true)}catch(e){status.textContent=err(e)}});
logout.addEventListener('click',async()=>{setMenu(false);await signOut(auth)});
document.querySelectorAll('[data-test-button]').forEach(b=>b.addEventListener('click',()=>{b.blur();window.dispatchEvent(new CustomEvent('mgd:monkey-button',{detail:{label:b.textContent.trim()}}))}));
onAuthStateChanged(auth,user=>{document.body.classList.remove('auth-pending');if(user){card.hidden=false;name.textContent=user.displayName||'Mi Gran Día';mail.textContent=user.email||'';if(user.photoURL){avatar.src=user.photoURL;avatar.hidden=false}else{avatar.hidden=true}}else{card.hidden=true;setMenu(false)}});